apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: frontend
    purpose: deployment-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      purpose: deployment-app1
  template:
    metadata:
      labels:
        app: frontend
        purpose: deployment-app1
    spec:
      containers:
        - name: app1-container
          image: vishnupriyadh/app1:1.0.0
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: frontend
    purpose: deployment-app1
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # Container port
---
# ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
  # annotation for ingress to handle loadbalancer, listener, rule and target group
    alb.ingress.kubernetes.io/scheme: internet-facing  # annotation - for internet facing
    alb.ingress.kubernetes.io/target-type: ip # annotation - target group instances are IP based hence ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]' # annotation for HTTPS. for HTTP  [{"HTTP": 80}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:529088271493:certificate/1b309286-9fe1-42e3-915f-8a23c1ac6097 # annotaion for certificate
    alb.ingress.kubernetes.io/group.name: joindevops
spec:
  ingressClassName: alb # ingressClassName should be alb always
  rules:
  - host: "app1.vishnudevopsaws.online"
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: app1
              port:
                name: use-annotation


          
