apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  # labels of deployment resource
  labels:
    app: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
        purpose: deployment-app2
    spec:
      containers:
        - name: app2-container
          image: vishnupriyadh/app2:1.0.0
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector: # labels are used as selectors
    app: app2
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # Container port
---
# ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations:
  # annotation for ingress to handle loadbalancer, listener, rule and target group
    alb.ingress.kubernetes.io/scheme: internet-facing # annotation - for internet facing
    alb.ingress.kubernetes.io/target-type: ip # annotation - target group instances are IP based hence ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]' # annotation for HTTPS. for HTTP  [{"HTTP": 80}]' or [{"HTTPS": 443}]
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:529088271493:certificate/15b7713a-7f60-4ab5-ae6b-ea2a806a4c09 # annotaion for certificate
    alb.ingress.kubernetes.io/group.name: vishnudevopsaws
spec:
  ingressClassName: alb # ingressClassName should be alb always
  rules:
  - host: "app2.vishnudevopsaws.online"
    http:
      paths:
      - pathType: Prefix
        path: "/"          
        backend:
          service:
            name: app2
            port:
              number: 80


          
